Ep02 minor fixes/typos
swcarpentry/python-novice-gapminder pull request #570
Opened 2021-09-11 17:44 UTC by vinisalazar

Hi,

Here are some minor fixes. If merged, this PR will:

- Close slice with bracket rather than parenthesis in descriptive text
- Add print statement to solution of 'Predicting Values' challenge
- Fix punctuation of 'Slicing Concepts' challenge

Best,
Vini

2021-09-13 21:29 UTC, alee requested changes
Thanks for the PR! I would like to get https://github.com/swcarpentry/python-novice-gapminder/issues/460 merged in first and discuss the issues with the slice interval notation

2021-09-13 21:29 UTC, alee commented on _episodes/02-variables.md
> +*   Mathematically, you might say that a slice selects `[start:stop]`.
The `[start:stop)` expression (which is invalid Python syntax) refers to [mathematical interval notation](https://en.wikipedia.org/wiki/Interval_(mathematics)#Notations_for_intervals) and means "include the value at `start`, but do not include the value at `stop`". If this is confusing to others however I'm open to adding a footnote or link or finding a different way to explain it.

2021-09-13 21:29 UTC, alee commented on _episodes/02-variables.md
>  > 3.  What does `thing[:high]` (without a value before the colon) do?
This PR will have some conflicts with https://github.com/swcarpentry/python-novice-gapminder/pull/567/files which I'd like to merge in as well - perhaps we can revisit it after that is merged?

2022-01-04 10:02 UTC, alex-ball commented
According to the Wikipedia link (and this is indeed how I remember it) mathematical interval notation uses a comma rather than a colon for separating the limits. To make it clearer that this isn't Python, perhaps it would be better to have `[start, stop)` or, even better, avoid the monospace and write it [*start*, *stop*).

2022-01-04 12:08 UTC, vahtras commented
We also have that a mathematical interval [x, y) is more like a set of
numbers and fundamentally different from a Python sequence of numbers where
there is an implied order.

On Tue, Jan 4, 2022 at 11:02 AM Alex Ball ***@***.***> wrote:

> According to the Wikipedia link (and this is indeed how I remember it)
> mathematical interval notation uses a comma rather than a colon for
> separating the limits. To make it clearer that this isn't Python, perhaps
> it would be better to have [start, stop) or, even better, avoid the
> monospace and write it [*start*, *stop*).
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/swcarpentry/python-novice-gapminder/pull/570#issuecomment-1004672259>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABLLJBOFK3ADZTJFY3YGXBTUULAVFANCNFSM5D3FQNDA>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2022-01-28 18:00 UTC, alee commented
> We also have that a mathematical interval [x, y) is more like a set of numbers and fundamentally different from a Python sequence of numbers where there is an implied order.

Based on this discussion I'm inclined to simply remove the entire statement as it seems to be muddying the waters more than clarifying anything 😅 

thanks for the feedback!

2022-01-28 18:00 UTC, alee approved these changes

2022-01-28 18:05 UTC, merged